name: traccar_manager
description: "Traccar Manager"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^7.2.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.2.0-beta.3
  flutter_secure_storage: ^11.0.0
  http: ^1.6.0
  local_auth: ^3.0.2
  path_provider: ^2.1.6
  permission_handler: ^13.0.0
  rate_my_app: ^2.4.1
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  shared_preferences_android: ^2.4.27
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
